// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdghmaeiqzhhdgsdvohk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkZ2htYWVpcXpoaGRnc2R2b2hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzM0OTAsImV4cCI6MjA2MzUwOTQ5MH0.edF2IXInuE4k7eaPw9ydV7iN4qdOOFpmbE2Gh5zT1BU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);